export const ErrorCodes = Object.freeze({
    PAYMENT_ALREADY_EXISTS: "PAYMENT_ALREADY_EXISTS",
    ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
    ORDER_ALREADY_PAID: "ORDER_ALREADY_PAID",
    INTERNAL_ERROR: "INTERNAL_ERROR",
})